"""Stable machine-readable reason codes.

Categories follow docs/design/11-rule-engine.md section 11.5.
IMAGE_READ_ERROR is an MVP pipeline addition used when an input image cannot
be decoded.
"""

from __future__ import annotations

BARCODE_UNREADABLE = "BARCODE_UNREADABLE"
PRODUCT_TYPE_UNKNOWN = "PRODUCT_TYPE_UNKNOWN"
PRODUCT_MAPPING_AMBIGUOUS = "PRODUCT_MAPPING_AMBIGUOUS"
PRODUCT_IDENTITY_UNVERIFIED = "PRODUCT_IDENTITY_UNVERIFIED"

CAMERA_DISCONNECTED = "CAMERA_DISCONNECTED"
NO_PRODUCT = "NO_PRODUCT"
MULTIPLE_PRODUCTS = "MULTIPLE_PRODUCTS"
ROI_INVALID = "ROI_INVALID"
INSUFFICIENT_VALID_FRAMES = "INSUFFICIENT_VALID_FRAMES"
INFERENCE_ERROR = "INFERENCE_ERROR"
IMAGE_READ_ERROR = "IMAGE_READ_ERROR"

COMPONENT_MISSING = "COMPONENT_MISSING"
COMPONENT_UNCERTAIN = "COMPONENT_UNCERTAIN"
COMPONENT_UNVERIFIABLE = "COMPONENT_UNVERIFIABLE"
COMPONENT_COUNT_INVALID = "COMPONENT_COUNT_INVALID"
COMPONENT_SPATIAL_INVALID = "COMPONENT_SPATIAL_INVALID"

RULE_NOT_FOUND = "RULE_NOT_FOUND"
CONFIG_INVALID = "CONFIG_INVALID"
VERSION_INCOMPATIBLE = "VERSION_INCOMPATIBLE"

INSPECTION_INTERRUPTED = "INSPECTION_INTERRUPTED"
DECISION_PERSISTENCE_FAILED = "DECISION_PERSISTENCE_FAILED"
RULE_EVALUATION_ERROR = "RULE_EVALUATION_ERROR"


def gate_failed(gate: str) -> str:
    """Compose a GATE_FAILED reason code for a named gate."""
    return f"GATE_FAILED:{gate}"


def component_reason(prefix: str, component_code: str) -> str:
    """Compose a per-component reason code."""
    return f"{prefix}:{component_code}"
